services:
  - type: web
    name: veetodo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "website:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false 